### ISSUE TITLE
Allow newer base versions

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [amcphail/hstatistics#5]
base-4.13.0.0 from stack configuration does not match >=4 && <4.11

**Comment by BebeSparkelSparkel** [comment]
I think you just need to push to hackage

**Comment by amcphail** [comment]
Hi,

Can you please provide a little more detail?  The cabal file asks for base >4 and <5.

Are you saying that the github version works but the one on hackage doesn't?

**Comment by BebeSparkelSparkel** [comment]
Yeah, when I link to the repo it builds but when I use the hackage version it has the <4.11 base constraint. I think if you just make a new release and then add it to hackage it will build again

**Comment by amcphail** [comment]
Should now be fixed.  Uploaded 0.3.1 to Hackage.  Apologies for the delay.
